server:
  port: 58081
  servlet:
    context-path: /redis

spring:
  application:
    name: redis

  data:
    redis:
      url: redis://127.0.0.1:6379
      database: 0
      timeout: 1000ms
      lettuce:
        pool:
          max-active: 1024
          max-idle: 200
          min-idle: 5
          time-between-eviction-runs: 2000ms
          max-wait: -1ms
      password:
      cluster:
        enabled: false
        max-redirects: 3
        nodes: 127.0.0.1:6379

  boot:
    admin:
      client:
        url: http://127.0.0.1:58086
        username:
        password:

management:
  endpoint:
    logfile:
      external-file: ./logs/client-info.log
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include: '*'

