server:
  port: 59000

logging:
  level:
    root: info
    com:
      alibaba:
        nacos: error

spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/mysql?useSSL=false&serverTimezone=Asia/Shanghai
    username: root
    password: qwer1234
  main:
    allow-circular-references: true

#mybatis:
#  configuration:
#    map-underscore-to-camel-case: true
#  type-aliases-package: cloud.spring.my.*.entity
#  mapper-locations: classpath:mapper/*.xml

mybatis-plus:
  mapper-locations: classpath:mapper/**/*.xml
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  type-aliases-package: cloud.spring.my.**.entity