@startuml
'https://plantuml.com/class-diagram

class Email
class Person

Person *-- Email

class Person {
    email: Email
    public void receive()
}

class Email {
    public String execReceive()
}

@enduml