server:
  port: 58080
  servlet:
    context-path: /short-domain

spring:
  application:
    name: short-domain
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/local?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimeZone=Asia/Shanghai
    username: root
    password: qwer1234

  boot:
    admin:
      client:
        url: http://127.0.0.1:58086
        username:
        password:

management:
  endpoint:
    logfile:
      external-file: ./logs/client-info.log
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include: '*'

mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    map-underscore-to-camel-case: true
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: cloud.spring.my.shortDomain.entities
